# Assets:
SPRITESHEET_PATH = "../../Assets/SpriteSheets/Legacy-Fantasy - High Forest 2.3/"


# Window settings
WINDOW_WIDTH, WINDOW_HEIGHT = 960, 540


SPEED_HERO = 4
ANIMSPEED_HERO_DEFAULT = 0.25
ANIMSPEED_HERO_IDLE = 0.1

SPEED_BEE = 2
ANIMSPEED_BEE = 0.2
